### PR TITLE
Feature/justin additions

### PR DESCRIPTION
**Pull request by happymelonbox**
Discuss as a team how you want to go ahead with these changes. Don't merge this unless you all agree to have this as your starting point.

I have obviously changed a bit stylistically.

Also, ignore the added file that says .vscode/settings.json. That's not supposed to be there

### CODE REVIEW

**Comment by Sakat808** [comment]
Thank you, Justin!  It help us a lot. As u say we will have a look and discuss it !

**Review by Sakat808 — COMMENTED** [review]
I think we could keep Sign Up anchor  and agree to  move h1 tag from new task button .

**Review by Sakat808 — COMMENTED** [review]
Yea, i notice this issue at beginning and quite confused about it! Good to know how to fix it. Thank you.

**Review by Sakat808 — COMMENTED** [review]
Quit silly, I don't like this website name! we will discuss come out a new website name.

**Review by Sakat808 — APPROVED** [review]
I agree with it.

**Review by Sakat808 — COMMENTED** [review]
Oh my god! Good to know just use right:50% to center the heading.  I search on the google can not find how to center the button. 
GOPV L 7I_F}2FAH9PYLDYP
 i want to center the submit and cancel button in center. How to do it?

**Review by Sakat808 — COMMENTED** [review]
I know how to do it! Forgot add this feature! Thank you. Maybe we can use other font style.

**Review by Sakat808 — COMMENTED** [review]
Little bit confuse about this change. Is this we use  https://fontawesome.com/. Like if i want create  a twitter logo use <i class="fa-brands fa-twitter"></i> .

**Review by Sakat808 — COMMENTED** [review]
Wa! Cool! I never thought we can use these much style in one! I think we can remove some unnecessary style like  -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-image: none;

**Review by Sakat808 — APPROVED** [review]

**Review by Sakat808 — COMMENTED** [review]
We need change the content!

**Review by Sakat808 — APPROVED** [review]

**Comment by happymelonbox** [comment]
> Little bit confuse about this change. Is this we use https://fontawesome.com/. Like if i want create a twitter logo use .

Hey Andy, sorry which part are you referring to here?

**Comment by happymelonbox** [comment]
> Quit silly, I don't like this website name! we will discuss come out a new website name.

haha fair enough, I wrote it after a few red wines so it's okay if you don't like it. You guys can call it whatever you want.

**Comment by happymelonbox** [comment]
> I think we could keep Sign Up anchor and agree to move h1 tag from new task button .

Sure you can definitely keep it if you want, a sign up/log in functionality is not something we will be implementing in this course but maybe one day you might like to link it to a database and use the sign up link. By all means.

**Pull request merged**
